-- Generated from scripts/wc2026-schedule.json. Paste into Supabase SQL editor.
-- Idempotent: re-running is safe.

begin;

-- Teams (48)
insert into public.teams (name, group_label) values
  ('Mexico', 'A'),
  ('South Africa', 'A'),
  ('Korea Republic', 'A'),
  ('Czechia', 'A'),
  ('Canada', 'B'),
  ('Bosnia and Herzegovina', 'B'),
  ('USA', 'D'),
  ('Paraguay', 'D'),
  ('Haiti', 'C'),
  ('Scotland', 'C'),
  ('Australia', 'D'),
  ('Türkiye', 'D'),
  ('Brazil', 'C'),
  ('Morocco', 'C'),
  ('Qatar', 'B'),
  ('Switzerland', 'B'),
  ('Côte d''Ivoire', 'E'),
  ('Ecuador', 'E'),
  ('Germany', 'E'),
  ('Curaçao', 'E'),
  ('Netherlands', 'F'),
  ('Japan', 'F'),
  ('Sweden', 'F'),
  ('Tunisia', 'F'),
  ('Saudi Arabia', 'H'),
  ('Uruguay', 'H'),
  ('Spain', 'H'),
  ('Cabo Verde', 'H'),
  ('IR Iran', 'G'),
  ('New Zealand', 'G'),
  ('Belgium', 'G'),
  ('Egypt', 'G'),
  ('France', 'I'),
  ('Senegal', 'I'),
  ('Iraq', 'I'),
  ('Norway', 'I'),
  ('Argentina', 'J'),
  ('Algeria', 'J'),
  ('Austria', 'J'),
  ('Jordan', 'J'),
  ('Ghana', 'L'),
  ('Panama', 'L'),
  ('England', 'L'),
  ('Croatia', 'L'),
  ('Portugal', 'K'),
  ('Congo DR', 'K'),
  ('Uzbekistan', 'K'),
  ('Colombia', 'K')
on conflict (name) do update set group_label = excluded.group_label;

-- Players (Golden Boot shortlist)
insert into public.players (name, team_id) select 'Kylian Mbappé', (select id from public.teams where name = 'France') where not exists (select 1 from public.players where name = 'Kylian Mbappé');
insert into public.players (name, team_id) select 'Lionel Messi', (select id from public.teams where name = 'Argentina') where not exists (select 1 from public.players where name = 'Lionel Messi');
insert into public.players (name, team_id) select 'Harry Kane', (select id from public.teams where name = 'England') where not exists (select 1 from public.players where name = 'Harry Kane');
insert into public.players (name, team_id) select 'Vinícius Júnior', (select id from public.teams where name = 'Brazil') where not exists (select 1 from public.players where name = 'Vinícius Júnior');
insert into public.players (name, team_id) select 'Lautaro Martínez', (select id from public.teams where name = 'Argentina') where not exists (select 1 from public.players where name = 'Lautaro Martínez');
insert into public.players (name, team_id) select 'Cristiano Ronaldo', (select id from public.teams where name = 'Portugal') where not exists (select 1 from public.players where name = 'Cristiano Ronaldo');
insert into public.players (name, team_id) select 'Lamine Yamal', (select id from public.teams where name = 'Spain') where not exists (select 1 from public.players where name = 'Lamine Yamal');
insert into public.players (name, team_id) select 'Erling Haaland', (select id from public.teams where name = 'Norway') where not exists (select 1 from public.players where name = 'Erling Haaland');
insert into public.players (name, team_id) select 'Mohamed Salah', (select id from public.teams where name = 'Egypt') where not exists (select 1 from public.players where name = 'Mohamed Salah');
insert into public.players (name, team_id) select 'Julián Álvarez', (select id from public.teams where name = 'Argentina') where not exists (select 1 from public.players where name = 'Julián Álvarez');

-- Matches (104) — upsert by fifa_match_number
insert into public.matches (fifa_match_number, stage, group_label, team_a_id, team_b_id, placeholder_a, placeholder_b, kickoff_at, match_order, stadium, city) values
  (1, 'group', 'A', (select id from public.teams where name = 'Mexico'), (select id from public.teams where name = 'South Africa'), 'A1', 'A2', '2026-06-11T19:00:00Z', 1, 'Mexico City Stadium', 'Mexico City'),
  (2, 'group', 'A', (select id from public.teams where name = 'Korea Republic'), (select id from public.teams where name = 'Czechia'), 'A3', 'UEFA PO D', '2026-06-12T02:00:00Z', 2, 'Guadalajara Stadium', 'Guadalajara'),
  (3, 'group', 'B', (select id from public.teams where name = 'Canada'), (select id from public.teams where name = 'Bosnia and Herzegovina'), 'B1', 'UEFA PO A', '2026-06-12T19:00:00Z', 3, 'Toronto Stadium', 'Toronto'),
  (4, 'group', 'D', (select id from public.teams where name = 'USA'), (select id from public.teams where name = 'Paraguay'), 'D1', 'D2', '2026-06-13T01:00:00Z', 4, 'Los Angeles Stadium', 'Los Angeles'),
  (5, 'group', 'C', (select id from public.teams where name = 'Haiti'), (select id from public.teams where name = 'Scotland'), 'C3', 'C4', '2026-06-14T01:00:00Z', 5, 'Boston Stadium', 'Boston'),
  (6, 'group', 'D', (select id from public.teams where name = 'Australia'), (select id from public.teams where name = 'Türkiye'), 'D3', 'UEFA PO C', '2026-06-14T04:00:00Z', 6, 'BC Place Vancouver', 'Vancouver'),
  (7, 'group', 'C', (select id from public.teams where name = 'Brazil'), (select id from public.teams where name = 'Morocco'), 'C1', 'C2', '2026-06-13T22:00:00Z', 7, 'New York/New Jersey Stadium', 'New York'),
  (8, 'group', 'B', (select id from public.teams where name = 'Qatar'), (select id from public.teams where name = 'Switzerland'), 'B3', 'B4', '2026-06-13T19:00:00Z', 8, 'San Francisco Bay Area Stadium', 'San Francisco Bay Area'),
  (9, 'group', 'E', (select id from public.teams where name = 'Côte d''Ivoire'), (select id from public.teams where name = 'Ecuador'), 'E3', 'E4', '2026-06-14T23:00:00Z', 9, 'Philadelphia Stadium', 'Philadelphia'),
  (10, 'group', 'E', (select id from public.teams where name = 'Germany'), (select id from public.teams where name = 'Curaçao'), 'E1', 'E2', '2026-06-14T17:00:00Z', 10, 'Houston Stadium', 'Houston'),
  (11, 'group', 'F', (select id from public.teams where name = 'Netherlands'), (select id from public.teams where name = 'Japan'), 'F1', 'F2', '2026-06-14T20:00:00Z', 11, 'Dallas Stadium', 'Dallas'),
  (12, 'group', 'F', (select id from public.teams where name = 'Sweden'), (select id from public.teams where name = 'Tunisia'), 'UEFA PO B', 'F4', '2026-06-15T02:00:00Z', 12, 'Monterrey Stadium', 'Monterrey'),
  (13, 'group', 'H', (select id from public.teams where name = 'Saudi Arabia'), (select id from public.teams where name = 'Uruguay'), 'H3', 'H4', '2026-06-15T22:00:00Z', 13, 'Miami Stadium', 'Miami'),
  (14, 'group', 'H', (select id from public.teams where name = 'Spain'), (select id from public.teams where name = 'Cabo Verde'), 'H1', 'H2', '2026-06-15T16:00:00Z', 14, 'Atlanta Stadium', 'Atlanta'),
  (15, 'group', 'G', (select id from public.teams where name = 'IR Iran'), (select id from public.teams where name = 'New Zealand'), 'G3', 'G4', '2026-06-16T01:00:00Z', 15, 'Los Angeles Stadium', 'Los Angeles'),
  (16, 'group', 'G', (select id from public.teams where name = 'Belgium'), (select id from public.teams where name = 'Egypt'), 'G1', 'G2', '2026-06-15T19:00:00Z', 16, 'Seattle Stadium', 'Seattle'),
  (17, 'group', 'I', (select id from public.teams where name = 'France'), (select id from public.teams where name = 'Senegal'), 'I1', 'I2', '2026-06-16T19:00:00Z', 17, 'New York/New Jersey Stadium', 'New York'),
  (18, 'group', 'I', (select id from public.teams where name = 'Iraq'), (select id from public.teams where name = 'Norway'), 'FIFA PO 2', 'I4', '2026-06-16T22:00:00Z', 18, 'Boston Stadium', 'Boston'),
  (19, 'group', 'J', (select id from public.teams where name = 'Argentina'), (select id from public.teams where name = 'Algeria'), 'J1', 'J2', '2026-06-17T01:00:00Z', 19, 'Kansas City Stadium', 'Kansas City'),
  (20, 'group', 'J', (select id from public.teams where name = 'Austria'), (select id from public.teams where name = 'Jordan'), 'J3', 'J4', '2026-06-17T04:00:00Z', 20, 'San Francisco Bay Area Stadium', 'San Francisco Bay Area'),
  (21, 'group', 'L', (select id from public.teams where name = 'Ghana'), (select id from public.teams where name = 'Panama'), 'L3', 'L4', '2026-06-17T23:00:00Z', 21, 'Toronto Stadium', 'Toronto'),
  (22, 'group', 'L', (select id from public.teams where name = 'England'), (select id from public.teams where name = 'Croatia'), 'L1', 'L2', '2026-06-17T20:00:00Z', 22, 'Dallas Stadium', 'Dallas'),
  (23, 'group', 'K', (select id from public.teams where name = 'Portugal'), (select id from public.teams where name = 'Congo DR'), 'K1', 'FIFA PO 1', '2026-06-17T17:00:00Z', 23, 'Houston Stadium', 'Houston'),
  (24, 'group', 'K', (select id from public.teams where name = 'Uzbekistan'), (select id from public.teams where name = 'Colombia'), 'K3', 'K4', '2026-06-18T02:00:00Z', 24, 'Mexico City Stadium', 'Mexico City'),
  (25, 'group', 'A', (select id from public.teams where name = 'Czechia'), (select id from public.teams where name = 'South Africa'), 'UEFA PO D', 'A2', '2026-06-18T16:00:00Z', 25, 'Atlanta Stadium', 'Atlanta'),
  (26, 'group', 'B', (select id from public.teams where name = 'Switzerland'), (select id from public.teams where name = 'Bosnia and Herzegovina'), 'B4', 'UEFA PO A', '2026-06-18T19:00:00Z', 26, 'Los Angeles Stadium', 'Los Angeles'),
  (27, 'group', 'B', (select id from public.teams where name = 'Canada'), (select id from public.teams where name = 'Qatar'), 'B1', 'B3', '2026-06-18T22:00:00Z', 27, 'BC Place Vancouver', 'Vancouver'),
  (28, 'group', 'A', (select id from public.teams where name = 'Mexico'), (select id from public.teams where name = 'Korea Republic'), 'A1', 'A3', '2026-06-19T01:00:00Z', 28, 'Guadalajara Stadium', 'Guadalajara'),
  (29, 'group', 'C', (select id from public.teams where name = 'Brazil'), (select id from public.teams where name = 'Haiti'), 'C1', 'C3', '2026-06-20T00:30:00Z', 29, 'Philadelphia Stadium', 'Philadelphia'),
  (30, 'group', 'C', (select id from public.teams where name = 'Scotland'), (select id from public.teams where name = 'Morocco'), 'C4', 'C2', '2026-06-19T22:00:00Z', 30, 'Boston Stadium', 'Boston'),
  (31, 'group', 'D', (select id from public.teams where name = 'Türkiye'), (select id from public.teams where name = 'Paraguay'), 'UEFA PO C', 'D2', '2026-06-20T03:00:00Z', 31, 'San Francisco Bay Area Stadium', 'San Francisco Bay Area'),
  (32, 'group', 'D', (select id from public.teams where name = 'USA'), (select id from public.teams where name = 'Australia'), 'D1', 'D3', '2026-06-19T19:00:00Z', 32, 'Seattle Stadium', 'Seattle'),
  (33, 'group', 'E', (select id from public.teams where name = 'Germany'), (select id from public.teams where name = 'Côte d''Ivoire'), 'E1', 'E3', '2026-06-20T20:00:00Z', 33, 'Toronto Stadium', 'Toronto'),
  (34, 'group', 'E', (select id from public.teams where name = 'Ecuador'), (select id from public.teams where name = 'Curaçao'), 'E4', 'E2', '2026-06-21T00:00:00Z', 34, 'Kansas City Stadium', 'Kansas City'),
  (35, 'group', 'F', (select id from public.teams where name = 'Netherlands'), (select id from public.teams where name = 'Sweden'), 'F1', 'UEFA PO B', '2026-06-20T17:00:00Z', 35, 'Houston Stadium', 'Houston'),
  (36, 'group', 'F', (select id from public.teams where name = 'Tunisia'), (select id from public.teams where name = 'Japan'), 'F4', 'F2', '2026-06-21T04:00:00Z', 36, 'Monterrey Stadium', 'Monterrey'),
  (37, 'group', 'H', (select id from public.teams where name = 'Uruguay'), (select id from public.teams where name = 'Cabo Verde'), 'H4', 'H2', '2026-06-21T22:00:00Z', 37, 'Miami Stadium', 'Miami'),
  (38, 'group', 'H', (select id from public.teams where name = 'Spain'), (select id from public.teams where name = 'Saudi Arabia'), 'H1', 'H3', '2026-06-21T16:00:00Z', 38, 'Atlanta Stadium', 'Atlanta'),
  (39, 'group', 'G', (select id from public.teams where name = 'Belgium'), (select id from public.teams where name = 'IR Iran'), 'G1', 'G3', '2026-06-21T19:00:00Z', 39, 'Los Angeles Stadium', 'Los Angeles'),
  (40, 'group', 'G', (select id from public.teams where name = 'New Zealand'), (select id from public.teams where name = 'Egypt'), 'G4', 'G2', '2026-06-22T01:00:00Z', 40, 'BC Place Vancouver', 'Vancouver'),
  (41, 'group', 'I', (select id from public.teams where name = 'Norway'), (select id from public.teams where name = 'Senegal'), 'I4', 'I2', '2026-06-23T00:00:00Z', 41, 'New York/New Jersey Stadium', 'New York'),
  (42, 'group', 'I', (select id from public.teams where name = 'France'), (select id from public.teams where name = 'Iraq'), 'I1', 'FIFA PO 2', '2026-06-22T21:00:00Z', 42, 'Philadelphia Stadium', 'Philadelphia'),
  (43, 'group', 'J', (select id from public.teams where name = 'Argentina'), (select id from public.teams where name = 'Austria'), 'J1', 'J3', '2026-06-22T17:00:00Z', 43, 'Dallas Stadium', 'Dallas'),
  (44, 'group', 'J', (select id from public.teams where name = 'Jordan'), (select id from public.teams where name = 'Algeria'), 'J4', 'J2', '2026-06-23T03:00:00Z', 44, 'San Francisco Bay Area Stadium', 'San Francisco Bay Area'),
  (45, 'group', 'L', (select id from public.teams where name = 'England'), (select id from public.teams where name = 'Ghana'), 'L1', 'L3', '2026-06-23T20:00:00Z', 45, 'Boston Stadium', 'Boston'),
  (46, 'group', 'L', (select id from public.teams where name = 'Panama'), (select id from public.teams where name = 'Croatia'), 'L4', 'L2', '2026-06-23T23:00:00Z', 46, 'Toronto Stadium', 'Toronto'),
  (47, 'group', 'K', (select id from public.teams where name = 'Portugal'), (select id from public.teams where name = 'Uzbekistan'), 'K1', 'K3', '2026-06-23T17:00:00Z', 47, 'Houston Stadium', 'Houston'),
  (48, 'group', 'K', (select id from public.teams where name = 'Colombia'), (select id from public.teams where name = 'Congo DR'), 'K4', 'FIFA PO 1', '2026-06-24T02:00:00Z', 48, 'Guadalajara Stadium', 'Guadalajara'),
  (49, 'group', 'C', (select id from public.teams where name = 'Scotland'), (select id from public.teams where name = 'Brazil'), 'C4', 'C1', '2026-06-24T22:00:00Z', 49, 'Miami Stadium', 'Miami'),
  (50, 'group', 'C', (select id from public.teams where name = 'Morocco'), (select id from public.teams where name = 'Haiti'), 'C2', 'C3', '2026-06-24T22:00:00Z', 50, 'Atlanta Stadium', 'Atlanta'),
  (51, 'group', 'B', (select id from public.teams where name = 'Switzerland'), (select id from public.teams where name = 'Canada'), 'B4', 'B1', '2026-06-24T19:00:00Z', 51, 'BC Place Vancouver', 'Vancouver'),
  (52, 'group', 'B', (select id from public.teams where name = 'Bosnia and Herzegovina'), (select id from public.teams where name = 'Qatar'), 'UEFA PO A', 'B3', '2026-06-24T19:00:00Z', 52, 'Seattle Stadium', 'Seattle'),
  (53, 'group', 'A', (select id from public.teams where name = 'Czechia'), (select id from public.teams where name = 'Mexico'), 'UEFA PO D', 'A1', '2026-06-25T01:00:00Z', 53, 'Mexico City Stadium', 'Mexico City'),
  (54, 'group', 'A', (select id from public.teams where name = 'South Africa'), (select id from public.teams where name = 'Korea Republic'), 'A2', 'A3', '2026-06-25T01:00:00Z', 54, 'Monterrey Stadium', 'Monterrey'),
  (55, 'group', 'E', (select id from public.teams where name = 'Curaçao'), (select id from public.teams where name = 'Côte d''Ivoire'), 'E2', 'E3', '2026-06-25T20:00:00Z', 55, 'Philadelphia Stadium', 'Philadelphia'),
  (56, 'group', 'E', (select id from public.teams where name = 'Ecuador'), (select id from public.teams where name = 'Germany'), 'E4', 'E1', '2026-06-25T20:00:00Z', 56, 'New York/New Jersey Stadium', 'New York'),
  (57, 'group', 'F', (select id from public.teams where name = 'Japan'), (select id from public.teams where name = 'Sweden'), 'F2', 'UEFA PO B', '2026-06-25T23:00:00Z', 57, 'Dallas Stadium', 'Dallas'),
  (58, 'group', 'F', (select id from public.teams where name = 'Tunisia'), (select id from public.teams where name = 'Netherlands'), 'F4', 'F1', '2026-06-25T23:00:00Z', 58, 'Kansas City Stadium', 'Kansas City'),
  (59, 'group', 'D', (select id from public.teams where name = 'Türkiye'), (select id from public.teams where name = 'USA'), 'UEFA PO C', 'D1', '2026-06-26T02:00:00Z', 59, 'Los Angeles Stadium', 'Los Angeles'),
  (60, 'group', 'D', (select id from public.teams where name = 'Paraguay'), (select id from public.teams where name = 'Australia'), 'D2', 'D3', '2026-06-26T02:00:00Z', 60, 'San Francisco Bay Area Stadium', 'San Francisco Bay Area'),
  (61, 'group', 'I', (select id from public.teams where name = 'Norway'), (select id from public.teams where name = 'France'), 'I4', 'I1', '2026-06-26T19:00:00Z', 61, 'Boston Stadium', 'Boston'),
  (62, 'group', 'I', (select id from public.teams where name = 'Senegal'), (select id from public.teams where name = 'Iraq'), 'I2', 'FIFA PO 2', '2026-06-26T19:00:00Z', 62, 'Toronto Stadium', 'Toronto'),
  (63, 'group', 'G', (select id from public.teams where name = 'Egypt'), (select id from public.teams where name = 'IR Iran'), 'G2', 'G3', '2026-06-27T03:00:00Z', 63, 'Seattle Stadium', 'Seattle'),
  (64, 'group', 'G', (select id from public.teams where name = 'New Zealand'), (select id from public.teams where name = 'Belgium'), 'G4', 'G1', '2026-06-27T03:00:00Z', 64, 'BC Place Vancouver', 'Vancouver'),
  (65, 'group', 'H', (select id from public.teams where name = 'Cabo Verde'), (select id from public.teams where name = 'Saudi Arabia'), 'H2', 'H3', '2026-06-27T00:00:00Z', 65, 'Houston Stadium', 'Houston'),
  (66, 'group', 'H', (select id from public.teams where name = 'Uruguay'), (select id from public.teams where name = 'Spain'), 'H4', 'H1', '2026-06-27T00:00:00Z', 66, 'Guadalajara Stadium', 'Guadalajara'),
  (67, 'group', 'L', (select id from public.teams where name = 'Panama'), (select id from public.teams where name = 'England'), 'L4', 'L1', '2026-06-27T21:00:00Z', 67, 'New York/New Jersey Stadium', 'New York'),
  (68, 'group', 'L', (select id from public.teams where name = 'Croatia'), (select id from public.teams where name = 'Ghana'), 'L2', 'L3', '2026-06-27T21:00:00Z', 68, 'Philadelphia Stadium', 'Philadelphia'),
  (69, 'group', 'J', (select id from public.teams where name = 'Algeria'), (select id from public.teams where name = 'Austria'), 'J2', 'J3', '2026-06-28T02:00:00Z', 69, 'Kansas City Stadium', 'Kansas City'),
  (70, 'group', 'J', (select id from public.teams where name = 'Jordan'), (select id from public.teams where name = 'Argentina'), 'J4', 'J1', '2026-06-28T02:00:00Z', 70, 'Dallas Stadium', 'Dallas'),
  (71, 'group', 'K', (select id from public.teams where name = 'Colombia'), (select id from public.teams where name = 'Portugal'), 'K4', 'K1', '2026-06-27T23:30:00Z', 71, 'Miami Stadium', 'Miami'),
  (72, 'group', 'K', (select id from public.teams where name = 'Congo DR'), (select id from public.teams where name = 'Uzbekistan'), 'FIFA PO 1', 'K3', '2026-06-27T23:30:00Z', 72, 'Atlanta Stadium', 'Atlanta'),
  (73, 'round_of_32', null, null, null, '2A', '2B', '2026-06-28T19:00:00Z', 73, 'Los Angeles Stadium', 'Los Angeles'),
  (74, 'round_of_32', null, null, null, '1E', '3ABCDF', '2026-06-29T20:30:00Z', 74, 'Boston Stadium', 'Boston'),
  (75, 'round_of_32', null, null, null, '1F', '2C', '2026-06-30T01:00:00Z', 75, 'Monterrey Stadium', 'Monterrey'),
  (76, 'round_of_32', null, null, null, '1C', '2F', '2026-06-29T17:00:00Z', 76, 'Houston Stadium', 'Houston'),
  (77, 'round_of_32', null, null, null, '1I', '3CDFGH', '2026-06-30T21:00:00Z', 77, 'New York/New Jersey Stadium', 'New York'),
  (78, 'round_of_32', null, null, null, '2E', '2I', '2026-06-30T17:00:00Z', 78, 'Dallas Stadium', 'Dallas'),
  (79, 'round_of_32', null, null, null, '1A', '3CEFHI', '2026-07-01T01:00:00Z', 79, 'Mexico City Stadium', 'Mexico City'),
  (80, 'round_of_32', null, null, null, '1L', '3EHIJK', '2026-07-01T16:00:00Z', 80, 'Atlanta Stadium', 'Atlanta'),
  (81, 'round_of_32', null, null, null, '1D', '3BEFIJ', '2026-07-02T00:00:00Z', 81, 'San Francisco Bay Area Stadium', 'San Francisco Bay Area'),
  (82, 'round_of_32', null, null, null, '1G', '3AEHIJ', '2026-07-01T20:00:00Z', 82, 'Seattle Stadium', 'Seattle'),
  (83, 'round_of_32', null, null, null, '2K', '2L', '2026-07-02T23:00:00Z', 83, 'Toronto Stadium', 'Toronto'),
  (84, 'round_of_32', null, null, null, '1H', '2J', '2026-07-02T19:00:00Z', 84, 'Los Angeles Stadium', 'Los Angeles'),
  (85, 'round_of_32', null, null, null, '1B', '3EFGIJ', '2026-07-03T03:00:00Z', 85, 'BC Place Vancouver', 'Vancouver'),
  (86, 'round_of_32', null, null, null, '1J', '2H', '2026-07-03T22:00:00Z', 86, 'Miami Stadium', 'Miami'),
  (87, 'round_of_32', null, null, null, '1K', '3DEIJL', '2026-07-04T01:30:00Z', 87, 'Kansas City Stadium', 'Kansas City'),
  (88, 'round_of_32', null, null, null, '2D', '2G', '2026-07-03T18:00:00Z', 88, 'Dallas Stadium', 'Dallas'),
  (89, 'round_of_16', null, null, null, 'W74', 'W77', '2026-07-04T21:00:00Z', 89, 'Philadelphia Stadium', 'Philadelphia'),
  (90, 'round_of_16', null, null, null, 'W73', 'W75', '2026-07-04T17:00:00Z', 90, 'Houston Stadium', 'Houston'),
  (91, 'round_of_16', null, null, null, 'W76', 'W78', '2026-07-05T20:00:00Z', 91, 'New York/New Jersey Stadium', 'New York'),
  (92, 'round_of_16', null, null, null, 'W79', 'W80', '2026-07-06T00:00:00Z', 92, 'Mexico City Stadium', 'Mexico City'),
  (93, 'round_of_16', null, null, null, 'W83', 'W84', '2026-07-06T19:00:00Z', 93, 'Dallas Stadium', 'Dallas'),
  (94, 'round_of_16', null, null, null, 'W81', 'W82', '2026-07-07T00:00:00Z', 94, 'Seattle Stadium', 'Seattle'),
  (95, 'round_of_16', null, null, null, 'W86', 'W88', '2026-07-07T16:00:00Z', 95, 'Atlanta Stadium', 'Atlanta'),
  (96, 'round_of_16', null, null, null, 'W85', 'W87', '2026-07-07T20:00:00Z', 96, 'BC Place Vancouver', 'Vancouver'),
  (97, 'quarter_final', null, null, null, 'W89', 'W90', '2026-07-09T20:00:00Z', 97, 'Boston Stadium', 'Boston'),
  (98, 'quarter_final', null, null, null, 'W93', 'W94', '2026-07-10T19:00:00Z', 98, 'Los Angeles Stadium', 'Los Angeles'),
  (99, 'quarter_final', null, null, null, 'W91', 'W92', '2026-07-11T21:00:00Z', 99, 'Miami Stadium', 'Miami'),
  (100, 'quarter_final', null, null, null, 'W95', 'W96', '2026-07-12T01:00:00Z', 100, 'Kansas City Stadium', 'Kansas City'),
  (101, 'semi_final', null, null, null, 'W97', 'W98', '2026-07-14T19:00:00Z', 101, 'Dallas Stadium', 'Dallas'),
  (102, 'semi_final', null, null, null, 'W99', 'W100', '2026-07-15T19:00:00Z', 102, 'Atlanta Stadium', 'Atlanta'),
  (103, 'third_place', null, null, null, 'RU101', 'RU102', '2026-07-18T21:00:00Z', 103, 'Miami Stadium', 'Miami'),
  (104, 'final', null, null, null, 'W101', 'W102', '2026-07-19T19:00:00Z', 104, 'New York/New Jersey Stadium', 'New York')
on conflict (fifa_match_number) do update set
  stage = excluded.stage, group_label = excluded.group_label,
  team_a_id = excluded.team_a_id, team_b_id = excluded.team_b_id,
  placeholder_a = excluded.placeholder_a, placeholder_b = excluded.placeholder_b,
  kickoff_at = excluded.kickoff_at, match_order = excluded.match_order,
  stadium = excluded.stadium, city = excluded.city;

-- Tournament config (dates derived from the schedule)
update public.tournament_config set name = 'FIFA World Cup 2026', starts_at = '2026-06-11T19:00:00Z', group_stage_ends_at = '2026-06-28T19:00:00Z' where id = 1;

commit;
